apiVersion: v1
kind: ConfigMap
metadata:
  name: buildplane-runtime-config
  labels:
    app.kubernetes.io/name: buildplane-runtime-config
    {{- include "buildplane.labels" . | nindent 4 }}
data:
  redis-url: {{ .Values.runtimeConfig.redisURL | quote }}
  migrations-dir: {{ .Values.runtimeConfig.migrationsDir | quote }}
  scheduler-batch-size: {{ .Values.runtimeConfig.schedulerBatchSize | quote }}
  scheduler-interval: {{ .Values.runtimeConfig.schedulerInterval | quote }}
  worker-lease-duration: {{ .Values.runtimeConfig.workerLeaseDuration | quote }}
  worker-drain-timeout: {{ .Values.runtimeConfig.workerDrainTimeout | quote }}
  ai-service-url: {{ .Values.runtimeConfig.aiServiceURL | quote }}
{{- if .Values.database.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildplane.databaseSecretName" . }}
  labels:
    app.kubernetes.io/name: buildplane-postgres
    {{- include "buildplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "buildplane.databaseSecretKey" . }}: {{ include "buildplane.databaseURL" . | quote }}
  {{- if .Values.postgres.enabled }}
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  database: {{ .Values.postgres.auth.database | quote }}
  {{- end }}
{{- end }}
